import { StyleSheet } from 'react-native';

export const rewardsStyles = StyleSheet.create({
  statsRow: { flexDirection: 'row', margin: 16, borderRadius: 16, padding: 14, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  statItem: { flex: 1, alignItems: 'center', gap: 4 },
  viewAllBtn: { marginHorizontal: 16, marginTop: 12, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  viewAllBtnText: { fontSize: 13, fontWeight: '700' },
  errorBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, marginTop: -4, marginBottom: 4, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  tabsRow: { flexDirection: 'row', borderRadius: 14, marginHorizontal: 16, marginTop: 4, padding: 4 },
  tabBtn: { flex: 1, borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
  tabBtnActive: { backgroundColor: '#007AFF' },
  tabText: { fontSize: 12, fontWeight: '700' },
  statValue: { fontSize: 18, fontWeight: '800' },
  statLabel: { fontSize: 10 },
  sectionTitle: { fontSize: 16, fontWeight: '800', paddingHorizontal: 16, marginTop: 20, marginBottom: 10 },
  emptyCard: { marginHorizontal: 16, borderRadius: 16, padding: 20, alignItems: 'center' },
  challengeCard: { marginHorizontal: 16, borderRadius: 16, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 },
  challengeTitle: { fontSize: 14, fontWeight: '700', marginBottom: 6 },
  claimBtn: { backgroundColor: '#16A34A', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, marginLeft: 10 },
  claimBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  progressTrack: { height: 6, borderRadius: 3, backgroundColor: 'rgba(128,128,128,0.15)', marginBottom: 4 },
  progressBar: { height: 6, borderRadius: 3, backgroundColor: '#3B82F6' },
  badgesGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 16, gap: 8 },
  badgeItem: { width: '30%' as any, borderRadius: 14, padding: 12, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(148,163,184,0.2)', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 1 },
  badgeName: { fontSize: 11, fontWeight: '600', marginTop: 4 },
  offerCard: { marginHorizontal: 16, borderRadius: 16, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 },
  offerBiz: { fontSize: 15, fontWeight: '700' },
  tripCard: { marginHorizontal: 16, borderRadius: 16, padding: 14, marginBottom: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 },
  tripRoute: { fontSize: 14, fontWeight: '600' },
  insightsCard: { marginHorizontal: 16, borderRadius: 16, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 },
  insightsRow: { flexDirection: 'row' },
  insightItem: { flex: 1, alignItems: 'center' },
  insightVal: { fontSize: 20, fontWeight: '800' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(2,6,23,0.62)', justifyContent: 'center', alignItems: 'center' },
  modalCard: { width: '75%', borderRadius: 20, padding: 24, alignItems: 'center' },
  modalSheet: { position: 'absolute', bottom: 0, left: 0, right: 0, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, paddingBottom: 40 },
  modalHandle: { width: 36, height: 4, backgroundColor: '#444', borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 20, fontWeight: '800', marginBottom: 8, textAlign: 'center' },
  navBtn: { backgroundColor: '#3B82F6', borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  navBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  fullSheet: { position: 'absolute', top: 72, left: 0, right: 0, bottom: 0, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingTop: 12 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingBottom: 12 },
  sheetTitle: { fontSize: 18, fontWeight: '800' },
  historyStats: { marginHorizontal: 16, marginBottom: 10, borderRadius: 16, padding: 12, gap: 4 },
  historyStatText: { fontSize: 12, fontWeight: '600' },
  modalHero: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
  modalHeroTitle: { fontSize: 42, fontWeight: '800', color: '#fff', marginBottom: 14 },
  modalHeroStatsRow: { flexDirection: 'row', gap: 10 },
  modalHeroStatCard: { flex: 1, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', paddingVertical: 12 },
  modalHeroStatValue: { fontSize: 26, color: '#fff', fontWeight: '800' },
  modalHeroStatLabel: { fontSize: 11, color: 'rgba(255,255,255,0.78)', marginTop: 4, fontWeight: '600' },
  modalTabRow: { flexDirection: 'row', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(148,163,184,0.35)' },
  modalTabBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 14 },
  modalTabBtnActive: { borderBottomWidth: 3, borderBottomColor: '#007AFF' },
  modalTabText: { fontSize: 16, fontWeight: '700' },
  nativeBadgeCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 16, borderWidth: 1, borderColor: 'rgba(148,163,184,0.25)', padding: 14, marginBottom: 10 },
  nativeBadgeIconWrap: { width: 56, height: 56, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 12, backgroundColor: 'rgba(148,163,184,0.13)' },
  nativeBadgeTitle: { fontSize: 18, fontWeight: '700' },
  nativeBadgeDesc: { marginTop: 2, fontSize: 12 },
  nativeProgressTrack: { marginTop: 10, height: 10, borderRadius: 999, backgroundColor: 'rgba(148,163,184,0.25)', overflow: 'hidden' },
  nativeProgressFill: { height: '100%', borderRadius: 999, backgroundColor: '#CBD5E1' },
  nativeProgressText: { fontSize: 11, marginTop: 6, textAlign: 'right', fontWeight: '700' },
});
