import type { OrionCompanionEventType, DialogueVariant } from './types';

export const DIALOGUE_VARIANTS: Record<OrionCompanionEventType, DialogueVariant[]> = {
  drive_started: [
    { id: 'ds1', patternKey: 'eta-banter', template: '{{userName}}, {{destination}} in about {{etaMinutes}} min. I will handle the road commentary.', moods: ['witty'], phases: ['opening'], maxStress: 'low', weight: 1.25 },
    { id: 'ds2', patternKey: 'route-chaos', template: 'Route set for {{destination}}. If traffic chooses chaos, I will file the complaint.', moods: ['sassy', 'witty'], phases: ['opening'], maxStress: 'low', weight: 1.2 },
    { id: 'ds3', patternKey: 'quiet-useful', template: 'Heading to {{destination}}. Directions first, jokes only when the road behaves.', moods: ['focused', 'calm'], phases: ['opening'] },
    { id: 'ds4', patternKey: 'snaproad-ready', template: 'SnapRoad is awake. Destination locked, gems possible, drama optional.', moods: ['hype', 'sassy'], phases: ['opening'], maxStress: 'low' },
    { id: 'ds5', patternKey: 'morning', template: 'Good {{timeOfDay}}, {{userName}}. Smooth miles to {{destination}} would be a classy start.', moods: ['witty', 'calm'], phases: ['opening'], maxStress: 'low' },
    { id: 'ds6', patternKey: 'calm-watch', template: 'Navigation live. I will watch traffic; you keep the wheel work clean.', moods: ['focused', 'calm'], phases: ['opening'] },
    { id: 'ds7', patternKey: 'passenger-seat', template: 'Passenger-seat Orion reporting in. Helpful, lightly judgmental, never over the turns.', moods: ['sassy'], phases: ['opening'], maxStress: 'low', weight: 1.1 },
    { id: 'ds8', patternKey: 'eta-clean', template: '{{destination}} is about {{etaMinutes}} min out. Clean drive, clean score energy.', moods: ['hype', 'witty'], phases: ['opening'], maxStress: 'low' },
    { id: 'ds9', patternKey: 'quiet-night', template: 'Night drive mode. I will keep it short and useful.', moods: ['quiet'], phases: ['opening'] },
    { id: 'ds10', patternKey: 'mode-aware', template: '{{drivingMode}} mode noted. I will match the vibe, minus any nonsense.', moods: ['witty', 'sassy'], phases: ['opening'], maxStress: 'low' },
    { id: 'ds11', patternKey: 'traffic-watch', template: 'Route started. I will call out the useful stuff and ignore the tiny road gossip.', moods: ['calm', 'focused'], phases: ['opening'] },
    { id: 'ds12', patternKey: 'destination-name', template: 'Alright {{userName}}, wheels pointed at {{destination}}. Let us keep this elegant.', moods: ['hype', 'witty'], phases: ['opening'], maxStress: 'low' },
  ],
  smooth_drive: [
    { id: 'sd1', patternKey: 'suspicious-road', template: 'Smooth ride so far. The road is behaving. Suspicious, but we will take it.', moods: ['witty', 'sassy'], phases: ['cruising'], maxStress: 'low', weight: 1.35 },
    { id: 'sd2', patternKey: 'tree-narration', template: 'Quiet stretch. I promise not to narrate every tree like a travel documentary.', moods: ['witty'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd3', patternKey: 'road-behaving', template: '{{currentRoad}} is behaving. Rare footage. Enjoy the peace.', moods: ['sassy', 'witty'], phases: ['cruising'], maxStress: 'medium' },
    { id: 'sd4', patternKey: 'future-self', template: 'Still smooth. Your future self appreciates the no-drama driving.', moods: ['calm'], phases: ['cruising'] },
    { id: 'sd5', patternKey: 'vibes', template: 'Easy miles. I brought route sense and a responsible amount of attitude.', moods: ['sassy', 'hype'], phases: ['cruising'], maxStress: 'low', requiresOpenedWithLine: true },
    { id: 'sd6', patternKey: 'coffee-logic', template: 'All calm out here. If coffee becomes a mission, I support the plot.', moods: ['witty'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd7', patternKey: 'drama-free', template: '{{userName}}, this stretch is suspiciously drama-free. Do not scare it.', moods: ['sassy', 'witty'], phases: ['cruising'], maxStress: 'low', weight: 1.15 },
    { id: 'sd8', patternKey: 'eta-cruise', template: 'Still about {{etaMinutes}} min to {{destination}}. Cruise is looking clean.', moods: ['calm', 'focused'], phases: ['cruising'], maxStress: 'medium' },
    { id: 'sd9', patternKey: 'distance-check', template: 'Mid-trip check: {{distanceMiles}} mi left. Calm-driver energy remains undefeated.', moods: ['hype', 'witty'], phases: ['cruising'] },
    { id: 'sd10', patternKey: 'snaproad-score', template: 'This is the kind of smooth stretch SnapRoad likes to reward quietly.', moods: ['hype', 'calm'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd11', patternKey: 'weather', template: '{{weather}} up here, {{trafficLevel}} traffic, and no plot twist yet.', moods: ['witty'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd12', patternKey: 'quiet-minimal', template: 'Smooth stretch. I will keep the cabin calm.', moods: ['quiet', 'calm'], phases: ['cruising'] },
    { id: 'sd13', patternKey: 'destination', template: '{{destination}} is still on schedule. Tiny miracle, normal Tuesday.', moods: ['sassy', 'witty'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd14', patternKey: 'sport-mode', template: '{{drivingMode}} mode and smooth roads. Fancy, but let us stay humble.', moods: ['sassy'], phases: ['cruising'], maxStress: 'low' },
    { id: 'sd15', patternKey: 'quiet-eta', template: 'Cruise is steady. About {{etaMinutes}} min left.', moods: ['quiet', 'calm'], phases: ['cruising'] },
    { id: 'sd16', patternKey: 'quiet-road', template: '{{currentRoad}} looks calm. I will stay light.', moods: ['quiet'], phases: ['cruising'], maxStress: 'medium' },
  ],
  heavy_traffic: [
    { id: 'ht1', patternKey: 'brake-parade', template: 'Ah yes, the brake-light parade. Still about {{etaMinutes}} min to {{destination}}.', moods: ['focused', 'calm'], phases: ['stressed', 'cruising'], maxStress: 'medium' },
    { id: 'ht2', patternKey: 'deep-breaths', template: 'Congestion ahead. Deep breaths; the route is still doing its job.', moods: ['calm', 'focused'], phases: ['stressed'] },
    { id: 'ht3', patternKey: 'road-slow', template: 'Slow patch on {{currentRoad}}. I am watching the ETA so you can watch traffic.', moods: ['focused'], phases: ['stressed'] },
    { id: 'ht4', patternKey: 'backup-line', template: 'Backup ahead. Not glamorous, but we still have a clean line through it.', moods: ['focused', 'calm'], phases: ['stressed', 'cruising'] },
    { id: 'ht5', patternKey: 'quiet-traffic', template: 'Heavy traffic patch. I will keep it short unless something changes.', moods: ['quiet', 'calm'], phases: ['stressed'] },
    { id: 'ht6', patternKey: 'traffic-chaos', template: 'Traffic chose group project energy. We will keep it calm.', moods: ['focused'], phases: ['stressed'], maxStress: 'medium' },
    { id: 'ht7', patternKey: 'eta-useful', template: '{{trafficLevel}} traffic ahead. ETA is about {{etaMinutes}} min; no sudden hero moves.', moods: ['focused', 'calm'], phases: ['stressed'] },
    { id: 'ht8', patternKey: 'patient', template: 'This is a patience section, not a speed section. I will guide the useful bits.', moods: ['calm', 'focused'], phases: ['stressed'] },
  ],
  reroute: [
    { id: 'rr1', patternKey: 'fresh-line', template: 'New route locked in. Follow the fresh line.', moods: ['focused', 'calm'], phases: ['stressed', 'opening'] },
    { id: 'rr2', patternKey: 'old-chaos', template: 'Rerouting. The old route chose chaos; we are not joining.', moods: ['focused'], phases: ['stressed'], maxStress: 'medium' },
    { id: 'rr3', patternKey: 'better-sequence', template: 'Route updated. No drama, just a better sequence.', moods: ['focused', 'calm'], phases: ['stressed', 'cruising'] },
    { id: 'rr4', patternKey: 'next-turns', template: 'Adjusted the plan. Next turns are the ones that matter.', moods: ['focused'], phases: ['stressed'] },
    { id: 'rr5', patternKey: 'cleaner-path', template: 'I found a cleaner path. Stay steady; I will call the next move.', moods: ['focused', 'calm'], phases: ['stressed'] },
    { id: 'rr6', patternKey: 'snaproad-replan', template: 'SnapRoad re-plan complete. The route had opinions; I had better data.', moods: ['focused'], phases: ['stressed'], maxStress: 'medium' },
    { id: 'rr7', patternKey: 'quiet-replan', template: 'Route changed. I will keep instructions clear from here.', moods: ['quiet', 'calm'], phases: ['stressed'] },
    { id: 'rr8', patternKey: 'destination-safe', template: 'Still headed to {{destination}}. Small detour, same mission.', moods: ['calm', 'focused'], phases: ['stressed', 'cruising'] },
  ],
  long_drive: [
    { id: 'ld1', patternKey: 'long-check', template: 'Long haul check-in: {{driveDurationMinutes}} min rolling. Still good?', moods: ['calm'], phases: ['cruising'] },
    { id: 'ld2', patternKey: 'hydrate', template: '{{driveDurationMinutes}} min in. Hydrate when it is safe, road legend.', moods: ['witty', 'calm'], phases: ['cruising'], maxStress: 'low' },
    { id: 'ld3', patternKey: 'marathon', template: 'Marathon mode. About {{distanceMiles}} mi left to {{destination}}.', moods: ['focused', 'calm'], phases: ['cruising'] },
    { id: 'ld4', patternKey: 'steady-energy', template: 'Steady driver energy. {{destination}} gets the victory lap, not the highway.', moods: ['hype', 'calm'], phases: ['cruising'] },
    { id: 'ld5', patternKey: 'road-snack', template: 'This drive has chapters now. Snack strategy later, eyes first.', moods: ['witty'], phases: ['cruising'], maxStress: 'low' },
    { id: 'ld6', patternKey: 'quiet-long', template: 'Long drive noted. I will keep check-ins rare and useful.', moods: ['quiet', 'calm'], phases: ['cruising'] },
    { id: 'ld7', patternKey: 'time-of-day', template: '{{timeOfDay}} miles hit different. Still tracking {{destination}}.', moods: ['witty', 'calm'], phases: ['cruising'] },
    { id: 'ld8', patternKey: 'calm-driver', template: '{{driveDurationMinutes}} min in and still smooth. That is grown-driver cinema.', moods: ['sassy', 'hype'], phases: ['cruising'], maxStress: 'low' },
  ],
  reward_earned: [
    { id: 'rw1', patternKey: 'gems-count', template: '{{gemsEarnedThisTrip}} gems this trip. Tiny road treasure, officially collected.', moods: ['hype', 'witty'], phases: ['cruising', 'opening'], weight: 1.25 },
    { id: 'rw2', patternKey: 'safe-miles', template: 'Gem alert. Safe miles are paying off.', moods: ['hype', 'calm'], phases: ['cruising'] },
    { id: 'rw3', patternKey: 'stacked-gems', template: 'You just stacked gems. Smooth pace, shiny results.', moods: ['hype'], phases: ['cruising'] },
    { id: 'rw4', patternKey: 'rewards-tick', template: 'Rewards ticking up: {{gemsEarnedThisTrip}} gems on this drive.', moods: ['hype', 'focused'], phases: ['cruising'] },
    { id: 'rw5', patternKey: 'snaproad-treasure', template: 'SnapRoad saw that. Gems added, little victory stored.', moods: ['hype', 'witty'], phases: ['cruising'] },
    { id: 'rw6', patternKey: 'quiet-reward', template: 'Gems added. Nice and smooth.', moods: ['quiet', 'calm'], phases: ['cruising'] },
    { id: 'rw7', patternKey: 'sassy-reward', template: 'Look at you collecting gems without making traffic worse. Elegant.', moods: ['sassy', 'hype'], phases: ['cruising'], maxStress: 'low' },
    { id: 'rw8', patternKey: 'score-energy', template: 'That drive behavior has score energy. Gems confirmed.', moods: ['hype'], phases: ['cruising'] },
  ],
  arrival: [
    { id: 'ar1', patternKey: 'clean-finish', template: 'You made it to {{destination}}. Clean finish.', moods: ['calm', 'hype'], phases: ['closing'] },
    { id: 'ar2', patternKey: 'dial-down', template: 'Arrived at {{destination}}. I will dial the energy down.', moods: ['calm', 'quiet'], phases: ['closing'] },
    { id: 'ar3', patternKey: 'park-safe', template: 'Destination reached. Park safe, stretch if you can.', moods: ['calm', 'focused'], phases: ['closing'] },
    { id: 'ar4', patternKey: 'done-good', template: '{{destination}} done. Good drive.', moods: ['calm', 'quiet'], phases: ['closing'] },
    { id: 'ar5', patternKey: 'no-plot-twist', template: 'We made it. No dramatic plot twist from traffic today.', moods: ['witty', 'sassy'], phases: ['closing'], maxStress: 'low' },
    { id: 'ar6', patternKey: 'gems-arrival', template: 'Arrived. If gems showed up, they were deserved.', moods: ['hype', 'witty'], phases: ['closing'] },
    { id: 'ar7', patternKey: 'night-arrival', template: 'Made it. Quiet finish, safe parking.', moods: ['quiet', 'calm'], phases: ['closing'] },
    { id: 'ar8', patternKey: 'snaproad-finish', template: 'SnapRoad trip wrapped. Smooth exit from the road show.', moods: ['hype', 'witty'], phases: ['closing'] },
    { id: 'ar9', patternKey: 'eta-finish', template: 'About {{etaMinutes}} min of road time handled. Nice work.', moods: ['calm'], phases: ['closing'] },
  ],
  safety_caution: [
    { id: 'sf1', patternKey: 'hazard-eyes', template: 'Heads up: hazard reported ahead. Eyes on the road.', moods: ['calm', 'focused'], phases: ['stressed', 'cruising'], maxStress: 'high' },
    { id: 'sf2', patternKey: 'clear-short', template: 'Caution ahead. I will keep directions clear and short.', moods: ['calm', 'focused'], phases: ['stressed'] },
    { id: 'sf3', patternKey: 'slow-early', template: 'Incident nearby. Slow down early if you can.', moods: ['calm', 'focused'], phases: ['stressed'] },
    { id: 'sf4', patternKey: 'stay-alert', template: 'Safety ping on your route. Stay alert.', moods: ['calm', 'focused'], phases: ['stressed', 'cruising'] },
    { id: 'sf5', patternKey: 'no-jokes', template: 'Possible issue ahead. I am keeping this simple: stay ready.', moods: ['calm', 'focused'], phases: ['stressed'] },
    { id: 'sf6', patternKey: 'quiet-safety', template: 'Caution ahead. Short instructions from here.', moods: ['quiet', 'calm'], phases: ['stressed'] },
    { id: 'sf7', patternKey: 'route-watch', template: 'Something is reported ahead. I will watch the route; you watch the road.', moods: ['focused'], phases: ['stressed'] },
  ],
  idle_checkin: [
    { id: 'ic1', patternKey: 'parked-recap', template: 'Parked mode. Want a recap, route idea, or gem gossip?', moods: ['witty'] },
    { id: 'ic2', patternKey: 'scores-gems', template: 'Not driving? I can help with scores, gems, or a quick route.', moods: ['calm'] },
    { id: 'ic3', patternKey: 'insights-ready', template: 'Still here. Insights look ready if you want the numbers.', moods: ['focused'] },
    { id: 'ic4', patternKey: 'stats-anytime', template: 'Off the road? Ask me about your SnapRoad stats anytime.', moods: ['calm'] },
    { id: 'ic5', patternKey: 'garage-energy', template: 'Quiet garage energy. Tap Orion when you are ready to plan.', moods: ['quiet'] },
    { id: 'ic6', patternKey: 'sassy-parked', template: 'The car is parked, so now I can have opinions safely.', moods: ['sassy', 'witty'] },
    { id: 'ic7', patternKey: 'route-brain', template: 'Need a route brain? Mine is available and mildly caffeinated.', moods: ['witty'] },
    { id: 'ic8', patternKey: 'snaproad-lobby', template: 'SnapRoad lobby mode. Scores, gems, routes - pick your side quest.', moods: ['hype', 'witty'] },
  ],
};
