import type { OrionCompanionEventType, DialogueVariant } from './types';

export const DIALOGUE_VARIANTS: Record<OrionCompanionEventType, DialogueVariant[]> = {
  drive_started: [
    { id: 'ds1', template: "Alright — {{destination}}. I'll keep it useful, not chatty.", phases: ['opening'] },
    { id: 'ds2', template: 'Trip on. About {{etaMinutes}} min if traffic behaves.', phases: ['opening'] },
    { id: 'ds3', template: "Let's roll to {{destination}}. I've got the boring updates.", phases: ['opening'] },
    {
      id: 'ds4',
      template: 'Navigation live. Ping me if you want a stop.',
      moods: ['witty', 'hype'],
      phases: ['opening'],
      maxStress: 'low',
    },
    { id: 'ds5', template: 'Heading to {{destination}}. Smooth line today would be nice.', phases: ['opening'] },
    {
      id: 'ds6',
      template: "{{userName}}, {{destination}} in about {{etaMinutes}} min — I'll keep the banter between turns.",
      phases: ['opening'],
      maxStress: 'low',
    },
    {
      id: 'ds7',
      template: 'Hey {{userName}} — wheels up. Smooth miles beat heroic lane changes.',
      moods: ['witty', 'hype'],
      phases: ['opening'],
      maxStress: 'low',
    },
    {
      id: 'ds8',
      template: '{{userName}}, we are pointed at {{destination}}. I will watch traffic so you watch the road.',
      phases: ['opening'],
    },
  ],
  smooth_drive: [
    {
      id: 'sd1',
      template: 'Cruise mode. The road is being suspiciously cooperative.',
      phases: ['cruising'],
      maxStress: 'low',
    },
    {
      id: 'sd2',
      template: 'Quiet stretch — I promise not to narrate every tree.',
      phases: ['cruising'],
      maxStress: 'low',
    },
    {
      id: 'sd3',
      template: '{{currentRoad}} is behaving. Enjoy the rare peace.',
      phases: ['cruising'],
      maxStress: 'medium',
    },
    {
      id: 'sd4',
      template: 'Still smooth. Your future self thanks you for not rushing.',
      phases: ['cruising'],
    },
    {
      id: 'sd5',
      template: 'Easy miles. I brought vibes, not spoilers.',
      moods: ['witty', 'hype'],
      phases: ['cruising'],
      maxStress: 'low',
      requiresOpenedWithLine: true,
    },
    { id: 'sd6', template: 'All calm out here. Holler if you want coffee logic.', phases: ['cruising'] },
    {
      id: 'sd7',
      template: '{{userName}}, this stretch is suspiciously drama-free. Enjoy it.',
      moods: ['witty', 'hype'],
      phases: ['cruising'],
      maxStress: 'low',
    },
    {
      id: 'sd8',
      template: 'Still about {{etaMinutes}} min to {{destination}}. Cruise looks good, {{userName}}.',
      phases: ['cruising'],
      maxStress: 'medium',
    },
    {
      id: 'sd9',
      template: 'Mid-trip check — {{distanceMiles}} mi left. You are doing the calm-driver thing well.',
      phases: ['cruising'],
    },
  ],
  heavy_traffic: [
    { id: 'ht1', template: 'Traffic thickened up — still about {{etaMinutes}} min to {{destination}}.', phases: ['stressed', 'cruising'] },
    { id: 'ht2', template: 'Congestion ahead. Deep breaths; we are still moving.', phases: ['stressed'] },
    { id: 'ht3', template: 'Slow zone on {{currentRoad}}. ETA drifted a bit — I am watching it.', phases: ['stressed'] },
    { id: 'ht4', template: 'Backup ahead. Not fun, but we have a line out.', phases: ['stressed', 'cruising'] },
    { id: 'ht5', template: 'Heavy traffic patch. I will stay quiet unless it changes.', phases: ['stressed'] },
  ],
  reroute: [
    { id: 'rr1', template: 'New route locked in. Follow the fresh line.', phases: ['stressed', 'opening'] },
    { id: 'rr2', template: 'Rerouting — I found a cleaner path. Stay with me.', phases: ['stressed'] },
    { id: 'rr3', template: 'Route updated. No drama, just a better sequence.', phases: ['stressed', 'cruising'] },
    { id: 'rr4', template: 'Adjusted the plan. Next turns are the ones that matter.', phases: ['stressed'] },
  ],
  long_drive: [
    { id: 'ld1', template: 'Long haul check-in — you have been rolling {{driveDurationMinutes}} minutes. Still good?', phases: ['cruising'] },
    { id: 'ld2', template: '{{driveDurationMinutes}} minutes in. Hydrate when it is safe.', phases: ['cruising'] },
    { id: 'ld3', template: 'Marathon mode. About {{distanceMiles}} mi left to {{destination}}.', phases: ['cruising'] },
    { id: 'ld4', template: 'Steady driver energy. We will celebrate at {{destination}}.', phases: ['cruising'] },
  ],
  reward_earned: [
    { id: 'rw1', template: '{{gemsEarnedThisTrip}} gems this trip so far — nice momentum.', phases: ['cruising', 'opening'] },
    { id: 'rw2', template: 'Gem alert. Safe miles are paying off.', phases: ['cruising'] },
    { id: 'rw3', template: 'You just stacked gems. Keep that smooth pace.', phases: ['cruising'] },
    { id: 'rw4', template: 'Rewards ticking up — {{gemsEarnedThisTrip}} gems on this drive.', phases: ['cruising'] },
  ],
  arrival: [
    { id: 'ar1', template: 'You made it to {{destination}}. Clean finish.', phases: ['closing'] },
    { id: 'ar2', template: 'Arrived at {{destination}}. I will dial the energy down.', phases: ['closing'], moods: ['calm', 'quiet'] },
    { id: 'ar3', template: 'Destination reached. Park safe, stretch if you can.', phases: ['closing'] },
    { id: 'ar4', template: '{{destination}} — done. Good drive.', moods: ['calm', 'quiet'], phases: ['closing'] },
    { id: 'ar5', template: 'Made it — about {{etaMinutes}} min of road time well spent.', phases: ['closing'] },
  ],
  safety_caution: [
    { id: 'sf1', template: 'Heads up — hazard reported ahead. Eyes on the road.', phases: ['stressed', 'cruising'], maxStress: 'high' },
    { id: 'sf2', template: 'Caution ahead. I will keep directions clear and short.', phases: ['stressed'] },
    { id: 'sf3', template: 'Incident nearby. Slow down early if you can.', phases: ['stressed'] },
    { id: 'sf4', template: 'Safety ping — something reported on your route. Stay alert.', phases: ['stressed', 'cruising'] },
  ],
  idle_checkin: [
    { id: 'ic1', template: 'Parked mode. Want a recap of your week or a route idea?' },
    { id: 'ic2', template: 'Hey — not driving? I can help with scores, gems, or a quick route.' },
    { id: 'ic3', template: 'Still here when you need me. Insights look ready if you scroll.' },
    { id: 'ic4', template: 'Off the road? Ask me about your SnapRoad stats anytime.' },
    { id: 'ic5', template: 'Quiet garage energy. Tap Orion when you are ready to plan.' },
  ],
};
